In [2]:
# 4 ways to multiply a pair of vectors
## dot product
## outer product
## element-wise multiplacation
## cross-product
import numpy as np
import matplotlib.pyplot as plt
import math as m

In [3]:
# dot product
# multiplication of all elements then summed
# 1*5 + 2*6 + 3*7 + 4*8
# 5 + 12 + 21 + 32 = 70
# The dot product is a single number that contains information on the relationship between 2 vectors
# 2 vectors -> scaler
# vectors must have same dimensionality
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.dot(v1,v2))
print(np.dot(v2,v1)) 
print(np.dot(v1,v1)) # ||a||^2 
print(m.sqrt(np.dot(v1,v1))) # ||a|| magnitude, length, norm of the vector

70
70
30
5.477225575051661


In [3]:
# Linear weighted combination
# scaler-vector multiplication and addition
l1 = 1
l2 = 2
l3 = -3
v1 = np.array([4,5,1])
v2 = np.array([-4,0,-4])
v3 = np.array([1,3,2])
print(l1*v1+l2*v2+l3*v3)

[ -7  -4 -13]


In [7]:
# Outer product

# Dot product: v^tW = 1x1 (Scaler)
# outer product: v*W^t = mxn
# used in eigen decomposition, singular value decomposition, image compression
# vectors do not need to be the same size in this case
v1 = np.array([2,5,4,7])
v2 = np.array([4,1,0,2])
op = np.outer(v1,v2)
print(op)

[[ 8  2  0  4]
 [20  5  0 10]
 [16  4  0  8]
 [28  7  0 14]]


In [8]:
# Element wise (Hadamard) vector product

# vectors need to be the same size in this case
# just a straight up multiplacation. Not , many theoretical uses in linear algebra
v1 = np.array([2,5,4,7])
v2 = np.array([4,1,0,2])
print(v1*v2)

[ 8  5  0 14]


In [25]:
# Unit Vector

# Vector with a length of 1 ||V|| = 1
# helps avoid numerical innacuracies for vectors with small magnitudes
# help create special kind of matrix called an orthoginal matrix.
# find a scaler that makes ||uv|| = 1, |u3| = 1 u = 1/3
# vhat = (1/||v||)*v --> (1/sqrt(sum1_to_N(v_i^2)))v

b = np.array([0,2])
bhat = (1/m.sqrt(sum([i**2 for i in b])))*b
print(bhat)

v = np.array([2,5,4,7])
vMAG = np.linalg.norm(v)
vhat = v / vMAG
print(vhat)

[0. 1.]
[0.20628425 0.51571062 0.4125685  0.72199487]
